site_name: Matthew Tobino
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  language: en
  ## Light mode and Dark Mode switch 
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mtobino
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthew-tobino-704a631b8/


# Future Copyright?
#copyright: |
##  &copy; 2023 <a href="https://github.com/mtobino"  target="_blank" rel="noopener">Matthew Tobino</a>