site_name: Matthew Tobino
theme:
  name: material
  favicon: img/favicon.ico
  icon:
    logo: :material-alpha-t-circle:
  features:
    - header.autohide
    - navigation.top
    - navigation.indexes
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  language: en
  ## Light mode and Dark Mode switch 
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: octicons/moon-16 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    # Dark Mode 
    - scheme: slate 
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons




extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mtobino
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthew-tobino-704a631b8/


# Future Copyright?
copyright: |
  &copy; 2023 <a href="https://github.com/mtobino"  target="_blank" rel="noopener">Matthew Tobino</a>
